# Generated by Django 4.1.3 on 2022-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
