# Generated by Django 4.1.3 on 2022-11-24 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name=datetime.date.today),
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, ex.'),
        ),
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.ImageField(default='', upload_to='form/images'),
        ),
        migrations.AddField(
            model_name='form',
            name='rol',
            field=models.CharField(default='Usuario público', max_length=50),
        ),
    ]
