# Generated by Django 4.1.3 on 2022-11-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_form_date_form_description_form_image_form_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(upload_to='main/images'),
        ),
    ]
