# Generated by Django 4.1.3 on 2022-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_form_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(default='/media/blog/images/headbands.jpg', upload_to='main/images'),
        ),
    ]
