# Generated by Django 4.1.3 on 2022-11-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_form_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(default='main/images/blazer.jpg', upload_to='main/images'),
        ),
    ]
