# Generated by Django 4.1.3 on 2022-12-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='role',
            field=models.CharField(default='Usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
