# Generated by Django 4.1.3 on 2022-12-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_form_role_alter_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='role',
        ),
    ]
