# Generated by Django 4.1.3 on 2022-12-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_form_subtitle_alter_form_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(),
        ),
    ]
