# Generated by Django 4.1.3 on 2022-12-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_alter_form_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='subtitle',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa omnis eveniet illum commodi officiis nulla soluta similique aliquid pariatur obcaecati iste autem quo nihil eius error assumenda porro, magnam fugiat nobis numquam. Repellendus nisi accusamus harum dolorum totam ipsum error.', max_length=500),
        ),
    ]
