# Generated by Django 4.1.3 on 2022-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rol',
            field=models.CharField(default='Administrador', max_length=50),
        ),
    ]
