# Generated by Django 4.1.3 on 2022-11-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='price',
        ),
    ]
