# Generated by Django 4.1.3 on 2022-11-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comingsoon_recommended'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comingsoon',
            new_name='NextMonth',
        ),
        migrations.DeleteModel(
            name='Recommended',
        ),
    ]
