# Generated by Django 4.1.3 on 2022-11-24 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_comingsoon_nextmonth_delete_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextmonth',
            name='price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.AddField(
            model_name='nextmonth',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name=datetime.date.today),
        ),
    ]
