# Generated by Django 4.1.3 on 2022-11-24 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_nextmonth_price_remove_project_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextmonth',
            name='date',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
