# Generated by Django 4.1.3 on 2022-12-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_nextmonth_date_alter_project_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextMonth',
        ),
    ]
