# Generated by Django 4.1.3 on 2022-12-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project_subtitle_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subtitle',
        ),
    ]
